version: "3"
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    networks:
      - net
  server1:
    image: node-app
    environment:
      - APPPORT=5001
      - SOCKETPORT=5003
    ports:
      - 5003:5003
    networks:
      - net
networks:
  net:
    driver: bridge